name: LightSuicide
version: '0.2'
main: ink.neokoni.lightSuicide.LightSuicide
api-version: '1.19'
folia-supported: true
authors: [Neokoni]
website: https://github.com/Craft233MC/LightSuicide


commands:
  suicide:
    description: kill yourself
    usage: /<command>
    permission: lightsuicide.suicide
    aliases: [sui, zisha, "自杀"]
  lightsuicide:
    description: lightsuicide manage
    usage: /<command> subcommands
    permission: lightsuicide.help
    aliases: [lsuicide, ls]

permissions:
  lightsuicide.suicide: {default: true}
  lightsuicide.about: {default: op}
  lightsuicide.help: {default: op}
  lightsuicide.reload: {default: op}
  lightsuicide.*:
    default: op
    children:
      lightsuicide.suicide: true
      lightsuicide.about: true
      lightsuicide.help: true
      lightsuicide.reload: true